const actionTypes = {
  personActions: {
    GET_PERSONS_START: "GET_PERSONS_START",
    GET_PERSONS_SUCCESS: "GET_PERSONS_SUCCESS",
    GET_PERSONS_FAIL: "GET_PERSONS_FAIL",
    DELETE_PERSONS_START: "DELETE_PERSONS_START",
    DELETE_PERSONS_SUCCESS: "DELETE_PERSONS_SUCCESS",
    DELETE_PERSONS_FAIL: "DELETE_PERSONS_FAIL",
    ADD_PERSON: "ADD_BOOK",
    EDIT_PERSON: "EDIT_PERSON",
  },
  groupActions: {
    GET_GROUPS_START: "GET_GROUPS_START",
    GET_GROUPS_SUCCESS: "GET_GROUPS_SUCCESS",
    GET_GROUPS_FAIL: "GET_GROUPS_FAIL",
  },
};

export default actionTypes;
